- hosts: all
  become: true
  tasks:
    - name: install packages
      package:
        name:
          - tcpdump
          - nftables
          - iptables-nft

- hosts: router
  become: true
  tasks:
    - name: create bridge device
      community.general.nmcli:
        type: bridge
        conn_name: br0
        ifname: br0
        state: present
        ip4:
          - 10.133.7.1/24

    - name: add bridge ports
      community.general.nmcli:
        type: bridge-slave
        conn_name: "bridge-port-{{ item }}"
        ifname: "{{ item }}"
        hairpin: false
        master: br0
        state: present
      loop:
        - eth2
        - eth3

    - name: configure eth1
      community.general.nmcli:
        type: ethernet
        conn_name: eth1
        ifname: eth1
        ip4:
          - 10.133.8.1/24
        state: present

    - name: configure ip forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        sysctl_set: true

    - name: configure firewall
      shell: |
        iptables -t nat -C POSTROUTING -s 10.133.7.0/24 -o eth0 -j MASQUERADE ||
        iptables -t nat -I POSTROUTING -s 10.133.7.0/24 -o eth0 -j MASQUERADE

        iptables -t nat -C POSTROUTING -s 10.133.8.0/24 -o eth0 -j MASQUERADE ||
        iptables -t nat -I POSTROUTING -s 10.133.8.0/24 -o eth0 -j MASQUERADE

- hosts: client:server
  become: true
  tasks:
    - name: configure eth0
      community.general.nmcli:
        type: ethernet
        conn_name: eth0
        ifname: eth0
        method4: auto
        never_default4: true
        state: present
      notify:
        - reload networking

    - name: configure eth1
      community.general.nmcli:
        type: ethernet
        conn_name: eth1
        ifname: eth1
        ip4:
          - "{{ ip_address }}"
        gw4: "{{ ip_address|nthhost(1) }}"
        state: present
      notify:
        - reload networking

  handlers:
    - name: reload networking
      shell: |
        nmcli n off && nmcli n on
